# Default values for bulklog.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: docker.pkg.github.com/khezen/bulklog/bulklog
  tag: 2.0.1
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""
appVersionOverride: ""
component: "service"
partOf: ""

replicaCount: 1

container:
  port: 5017

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - bulklog.local
  tls: []
  #  - secretName: bulklog-tls
  #    hosts:
  #      - bulklog.local

persistence: |
  enabled: false
  redis: 
    endpoint: redis:6379
    password: changeme #(optional)
    db: 0 #(optional, default: 0)

output: |
  elasticsearch:
    enabled: true
    endpoint: elasticsearch-client:9200
    scheme: http
  # aws_auth:
  #   access_key_id: changeme
  #   secret_access_key: changeme
  #   region: eu-west-1
  # basic_auth: 
  #   username: elastic
  #   password: changeme
  
collections: |
  - name: logs
    flush_period: 5 seconds # hours|minutes|seconds|milliseconds
    retention_period: 45 minutes
    shards: 5
    replicas: 1
    schemas:
      source: 
        type: string
        max_length: 64
      stream: 
        type: string
        length: 6
      event: 
        type: string
      time:
        type: datetime
        date_format: 2006-01-02T15:04:05.999999999Z07:00

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}


