apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bulklog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bulklog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ include "bulklog.appVersion" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.component }}
    app.kubernetes.io/component: {{ .Values.component }}
    {{- end}}
    {{- if .Values.partOf }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    {{- end}}
    helm.sh/chart: {{ include "bulklog.chart" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bulklog.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/version: {{ include "bulklog.appVersion" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bulklog.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/version: {{ include "bulklog.appVersion" . }}
        {{- if .Values.component }}
        app.kubernetes.io/component: {{ .Values.component }}
        {{- end}}
        {{- if .Values.partOf }}
        app.kubernetes.io/part-of: {{ .Values.partOf }}
        {{- end}}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /v1/liveness
              port: http
          readinessProbe:
            httpGet:
              path: /v1/readiness
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
