apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bulklog.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "bulklog.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ include "bulklog.appVersion" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- if .Values.component }}
    app.kubernetes.io/component: {{ .Values.component }}
    {{- end}}
    {{- if .Values.partOf }}
    app.kubernetes.io/part-of: {{ .Values.partOf }}
    {{- end}}
    helm.sh/chart: {{ include "bulklog.chart" . }}
type: Opaque
data: 
  config.yaml: |-
    port: {{ .Values.container.port }}
    
    persistence:
{{ .Values.persistence | indent 6 }}
    output:
{{ .Values.output | indent 6 }}
    collections:
{{ .Values.collections | indent 6 }}
  

 
